---
Name: passwordstrength
After: '#corepasswords'
---
# In the case someone uses `new PasswordValidator` instead of Injector, provide some safe defaults through config.
# Test names will not be set however, as it is not configurable.
SilverStripe\Security\PasswordValidator:
  min_length: 10
  min_test_score: 3
  historic_count: 6
# Set strength tests and requirements in line with NZISM
# Injector is used by default for Member password validation
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\PasswordValidator:
    properties:
      MinLength: 10
      MinTestScore: 3
      HistoricCount: 6
      TestNames:
        - lowercase
        - uppercase
        - digits
        - punctuation
